import type { DisplacementJourney } from '../types/index.ts';

export const SAMPLE_JOURNEYS: DisplacementJourney[] = [
  {
    id: 'journey-khartoum-portsudan-1',
    title: 'Ten Days of Hope: From Khartoum to Port Sudan',
    authorName: 'Tariq Al-Hassan',
    authorId: 'user-tariq',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    summary: 'When shelling intensified near our neighborhood in Al-Riyadh, Khartoum, my wife and three children packed two bags and started an arduous 1,120 km journey towards the Red Sea.',
    startLocation: 'Khartoum - Al-Riyadh',
    destination: 'Port Sudan',
    startDate: '2023-04-18 06:30',
    endDate: '2023-04-28 18:00',
    distanceKm: 1150,
    createdAt: '2023-05-05T10:00:00Z',
    isPublic: true,
    tags: ['Khartoum', 'Wad Madani', 'Gedaref', 'Port Sudan', 'Family Displacement'],
    familyMembersCount: 5,
    photos: [
      {
        id: 'photo-101',
        journeyId: 'journey-khartoum-portsudan-1',
        url: 'https://images.unsplash.com/photo-1572949645841-094f3a9c4c94?w=800&auto=format&fit=crop&q=80',
        filename: 'khartoum_departure.jpg',
        latitude: 15.5507,
        longitude: 32.5599,
        locationName: 'Khartoum - Al-Riyadh District',
        timestamp: '2023-04-18 07:15',
        caption: 'The last view of our apartment balcony as smoke rose over the skyline.',
        notes: 'We had 20 minutes to pack. We took family photos, key documents, and drinking water.',
        hasExif: true,
        order: 1
      },
      {
        id: 'photo-102',
        journeyId: 'journey-khartoum-portsudan-1',
        url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&auto=format&fit=crop&q=80',
        filename: 'wad_madani_bus.jpg',
        latitude: 14.4012,
        longitude: 33.5199,
        locationName: 'Wad Madani Bus Station',
        timestamp: '2023-04-19 14:00',
        caption: 'Arriving in Wad Madani after 10 hours on congested roads.',
        notes: 'Local volunteers gave us hot tea and bread. The town was hosting tens of thousands of fleeing families.',
        hasExif: true,
        order: 2
      },
      {
        id: 'photo-103',
        journeyId: 'journey-khartoum-portsudan-1',
        url: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?w=800&auto=format&fit=crop&q=80',
        filename: 'gedaref_stopover.jpg',
        latitude: 14.0349,
        longitude: 35.3834,
        locationName: 'Gedaref Agricultural Belt',
        timestamp: '2023-04-22 11:30',
        caption: 'Crossing Gedaref state towards Eastern Sudan.',
        notes: 'Fuel was scarce and prices surged, but strangers offered rides in pickup trucks to families with small children.',
        hasExif: true,
        order: 3
      },
      {
        id: 'photo-104',
        journeyId: 'journey-khartoum-portsudan-1',
        url: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&auto=format&fit=crop&q=80',
        filename: 'red_sea_mountains.jpg',
        latitude: 18.8000,
        longitude: 36.9000,
        locationName: 'Red Sea Hills Highway',
        timestamp: '2023-04-26 16:45',
        caption: 'The majestic Red Sea mountains signaling we were nearing safety.',
        notes: 'Cooler sea breeze brought immense emotional relief after days of sweltering heat.',
        hasExif: true,
        order: 4
      },
      {
        id: 'photo-105',
        journeyId: 'journey-khartoum-portsudan-1',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
        filename: 'port_sudan_harbor.jpg',
        latitude: 19.6158,
        longitude: 37.2164,
        locationName: 'Port Sudan Coastal Port',
        timestamp: '2023-04-28 17:30',
        caption: 'Safe arrival at Port Sudan Harbor.',
        notes: 'We found temporary shelter at a school hall turned relief center. A new chapter begins.',
        hasExif: true,
        order: 5
      }
    ]
  },
  {
    id: 'journey-omdurman-cairo-2',
    title: 'Northward Bound: From Omdurman to Cairo',
    authorName: 'Mona El-Tayeb',
    authorId: 'user-mona',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    summary: 'Documenting our 1,850 km northern journey through the Nubian Desert, crossing the Nile at Dongola, staying at Wadi Halfa border, and finally reaching Cairo.',
    startLocation: 'Omdurman - Al-Thawra',
    destination: 'Cairo, Egypt',
    startDate: '2023-05-02 08:00',
    endDate: '2023-05-18 20:00',
    distanceKm: 1850,
    createdAt: '2023-05-25T14:30:00Z',
    isPublic: true,
    tags: ['Omdurman', 'Dongola', 'Wadi Halfa', 'Ashkeet Border', 'Cairo', 'Egypt'],
    familyMembersCount: 4,
    photos: [
      {
        id: 'photo-201',
        journeyId: 'journey-omdurman-cairo-2',
        url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80',
        filename: 'omdurman_thawra.jpg',
        latitude: 15.6500,
        longitude: 32.4800,
        locationName: 'Omdurman - Al-Thawra District',
        timestamp: '2023-05-02 08:30',
        caption: 'Packing our vehicle early morning in Al-Thawra, Omdurman.',
        notes: 'Saying goodbye to our home of 25 years. We carried memory albums and essential medicines for my mother.',
        hasExif: true,
        order: 1
      },
      {
        id: 'photo-202',
        journeyId: 'journey-omdurman-cairo-2',
        url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
        filename: 'dongola_nile.jpg',
        latitude: 19.1764,
        longitude: 30.4739,
        locationName: 'Dongola - Nile Riverbank',
        timestamp: '2023-05-04 15:20',
        caption: 'Resting by the peaceful Nile riverbank in Dongola, Northern State.',
        notes: 'The hospitality of the Northern State residents warmed our hearts during a dark period.',
        hasExif: true,
        order: 2
      },
      {
        id: 'photo-203',
        journeyId: 'journey-omdurman-cairo-2',
        url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&auto=format&fit=crop&q=80',
        filename: 'wadi_halfa_queue.jpg',
        latitude: 21.7961,
        longitude: 31.3718,
        locationName: 'Wadi Halfa Town',
        timestamp: '2023-05-08 10:00',
        caption: 'Waiting at Wadi Halfa processing center.',
        notes: 'Spent 6 days in Wadi Halfa awaiting entry visa procedures. Families helped each other share meals and phone chargers.',
        hasExif: true,
        order: 3
      },
      {
        id: 'photo-204',
        journeyId: 'journey-omdurman-cairo-2',
        url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&auto=format&fit=crop&q=80',
        filename: 'ashkeet_border.jpg',
        latitude: 21.9880,
        longitude: 31.4240,
        locationName: 'Ashkeet / Argeen Border Crossing',
        timestamp: '2023-05-14 13:45',
        caption: 'Crossing the international border into Egyptian territory.',
        notes: 'A mixture of grief for leaving Sudan and relief for crossing safely.',
        hasExif: true,
        order: 4
      },
      {
        id: 'photo-205',
        journeyId: 'journey-omdurman-cairo-2',
        url: 'https://images.unsplash.com/photo-1572252821143-035a0247d4e3?w=800&auto=format&fit=crop&q=80',
        filename: 'cairo_arrival.jpg',
        latitude: 30.0444,
        longitude: 31.2357,
        locationName: 'Cairo - Faisal District',
        timestamp: '2023-05-18 19:30',
        caption: 'Reaching our rented flat in Cairo.',
        notes: 'Reunited with relatives who arrived a week earlier. Still praying for peace in Sudan so we can return home.',
        hasExif: true,
        order: 5
      }
    ]
  },
  {
    id: 'journey-bahri-kampala-3',
    title: 'The Southern Route: Bahri to Kampala via Renk',
    authorName: 'Omer Osman',
    authorId: 'user-omer',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    summary: 'My journey moving southward from Bahri, crossing the White Nile through Kosti, entering South Sudan via Renk, traveling to Juba, and settling temporarily in Uganda.',
    startLocation: 'Bahri - Shambat',
    destination: 'Kampala, Uganda',
    startDate: '2023-06-05 07:00',
    endDate: '2023-06-22 16:00',
    distanceKm: 1980,
    createdAt: '2023-07-01T09:15:00Z',
    isPublic: true,
    tags: ['Bahri', 'Kosti', 'Renk', 'Juba', 'Kampala', 'South Sudan', 'Uganda'],
    familyMembersCount: 3,
    photos: [
      {
        id: 'photo-301',
        journeyId: 'journey-bahri-kampala-3',
        url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
        filename: 'bahri_shambat.jpg',
        latitude: 15.6667,
        longitude: 32.5333,
        locationName: 'Bahri - Shambat Bridge Area',
        timestamp: '2023-06-05 07:30',
        caption: 'Early morning departure from Shambat, Bahri.',
        notes: 'Heavy artillery forced us to take the southern highway route towards White Nile State.',
        hasExif: true,
        order: 1
      },
      {
        id: 'photo-302',
        journeyId: 'journey-bahri-kampala-3',
        url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&auto=format&fit=crop&q=80',
        filename: 'kosti_white_nile.jpg',
        latitude: 13.1629,
        longitude: 32.6635,
        locationName: 'Kosti Bridge over the White Nile',
        timestamp: '2023-06-07 12:15',
        caption: 'Crossing the iconic Kosti bridge over the White Nile.',
        notes: 'Thousands of evacuees gathered at Kosti port waiting for river barges and buses.',
        hasExif: true,
        order: 2
      },
      {
        id: 'photo-303',
        journeyId: 'journey-bahri-kampala-3',
        url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&auto=format&fit=crop&q=80',
        filename: 'renk_transit.jpg',
        latitude: 11.8317,
        longitude: 32.8025,
        locationName: 'Renk Border Transit Center',
        timestamp: '2023-06-11 16:40',
        caption: 'Arrival at Renk transit point in South Sudan.',
        notes: 'Warm welcome by aid workers and local communities providing emergency relief packages.',
        hasExif: true,
        order: 3
      },
      {
        id: 'photo-304',
        journeyId: 'journey-bahri-kampala-3',
        url: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&auto=format&fit=crop&q=80',
        filename: 'juba_airport.jpg',
        latitude: 4.8594,
        longitude: 31.5713,
        locationName: 'Juba International Transit',
        timestamp: '2023-06-16 11:00',
        caption: 'In transit at Juba after traveling down the Nile corridor.',
        notes: 'Arranged transport to Kampala with fellow Sudanese university students.',
        hasExif: true,
        order: 4
      },
      {
        id: 'photo-305',
        journeyId: 'journey-bahri-kampala-3',
        url: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&auto=format&fit=crop&q=80',
        filename: 'kampala_settlement.jpg',
        latitude: 0.3476,
        longitude: 32.5825,
        locationName: 'Kampala - Kansanga District',
        timestamp: '2023-06-22 15:30',
        caption: 'Setting up our temporary stay in Kampala.',
        notes: 'Grateful for safety and peace. Continuing our education while holding Sudan in our hearts.',
        hasExif: true,
        order: 5
      }
    ]
  }
];
